### ISSUE TITLE
Providing data in a reproducible way 

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/Adv_Reproducibility_in_Cancer_Informatics#11]
## Describe the your scope of your content idea

This will explain some basics around how to make your data available (GitHub won't work). 
This chapter will be short and cover the basics but then will point to @carriewright11 's chapters. 

## Describe the learning objectives for your content idea

- How to supply a data-download script 
- How to share data

**Comment by carriewright11** [comment]
yeah we should maybe talk about what you would like to be included

**Comment by cansavvy** [comment]
I can definitely help co-author if we compare our lists of what should be discussed.

**Comment by carriewright11** [comment]
lol what if ends up being more courses :P jk
